POST http://localhost:8080/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    "query": "query {
        categoryById(id: \"854d9fa3-6005-455f-8451-0bcf6cd7976e\") {
            name
            id
        }
    }"
}